name = "New Pack Create"
author = "sammy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44ff6e0d571306049a1bf316182690417bd63eceb2da9e45f98d7f612e6aa66d"

[versions]
fabric = "0.15.3"
minecraft = "1.19.2"
