name = "New Pack Create"
author = "sammy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5f5ecce69a30c61c87fb4d1e0758b13d3a2f7a43a858f30617821ce8d836e32"

[versions]
fabric = "0.15.3"
minecraft = "1.19.2"
